<!DOCTYPE html>
<html lang=en>
<head>
	<meta charset=UTF-8>
	<meta name=viewport content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
	<meta name="keywords" content="gifiles, stratfor, wikileaks-press, search engine, wikileaks, full, text, search">
	<meta name="description" content="A tool allowing you to perform full-text search and browse the leaked GIFiles released by Wikileaks">


	<title>WLPress - Article Database</title>
	
	<!-- The framework -->
	<link rel=stylesheet href=../core/css/inuit.css>
	<!-- Plugins -->
	<link rel=stylesheet href=css/igloos.css>
	<!-- style -->
	<link rel=stylesheet href=css/style.css>
</head>
<body class=wrapper>
	
	<div class=header>
       <center>
<a href="http://wikileaks-press.org/" class=logo title="Visit our homepage"><img src=img/logo.png alt="WLPress logo"></a>
        <br />
		<?
			include_once('./inc/functions.inc.php');
			foreach($menu as $label => $link)
			echo "- <a href='".$link."'>".$label."</a> ";
		?>
        <?
        echo "-";
        ?>
      </center>
	</div>

	<div class=grids>
		<div class=grid-12>
			
            <p></p>            
			
			<h2>About</h2>
			
<p>WikiLeaks Press is an unofficial volunteer-run organization endorsed by
WikiLeaks.</p>

<h2>About the articles adder</h2>

<h3>What is the articles adder?</h3>
<p>The WikiLeaks Press article adder is a Firefox plugin which allows
anyone who installs it to insert articles into a curated articles database
of media coverage of WikiLeaks material. Those who use the article adder
can add metadata such as keyword tags, publication date, author, and full
text. The articles are fed into our RSS feed and are available for
searching by keyword.</p>

<p>In theory, this concept and plugin could be developed for any number of
focus issues interested in combating the wide dispersion of information
accross the internet by making a similar archive available in one place
for information gathering.</p>

<h3>Why curate an articles archive?</h3>
<p>A commonly held misconception is that information, once on the
internet, is there eternally. However, on the contrary, articles even from
the mainstream media are often deleted, disappeared behind paywalls, or
rendered unfindable in the mass of information accumulating accross the
internet.</p>

<p>In the case of WikiLeaks, significant findings published in media based
on leaks are sometimes drowned out by articles on Julian Assange and his
personal situation. Anyone seeking to find information on the impact of
the release of State Department cables referring to Kenya, for example,
may be unable to find all relevant articles only a few months after
significant movement within Kenyan political circles due to cables
documenting corruption of Kenyan politicians. Our database allows
interested parties to pull up such articles through a simple search.</p>

<p>A more general view of the database may be able to demonstrate how much
interest in certain topics were generated in the media shortly after a
leak and how sustained that interest has been over time.</p>

<p>One result of the disappearance of information on the net is a tendency
to "forget". News cycles are generated by mainstream media. These cycles
are created such that every year, a potential Israeli attack on Iran is
presented as a breaking new development. Information is not allowed to
build upon itself for context, for culture, or continuity. In addition,
peaked community-driven interest on a topic at a particular moment in time
is basically lost. We would like to enable interested parties to curate a
searchable archive of information - from articles, blogs, and studies -
which will NOT be lost, and which serve as a historical record of interest
on a focused issue.</p>

			
		</div><!-- /grid-6 -->
<hr>		
		<div class=grids>

		
		</div><!-- /grids -->
	
	<div class=footer>
		<p>This tool is provided by <a href="http://wikileaks-press.org/">WikiLeaks-Press</a>, <a href="https://www.cabledrum.net/">cabledrum</a> and various other contributors.</p>
	</div>
	
</body>
</html>
