------------------------------------------------------------------------
-- wlpressdb -- WikiLeaks Press news archive database -- version 0.80 --
------------------------------------------------------------------------

-- wlpressdb publishing media
-- version 0.80 for PostgreSQL 8.3
-- 2012-02-25
-- author: Cabledrummer <jack.rabbit@cabledrum.net>


SET client_encoding = 'UTF8';
SET standard_conforming_strings = off;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;
SET default_tablespace = '';
SET default_with_oids = false;


-- table media ---------------------------------------------------------

INSERT INTO media (media_key, media_en, media_nt, sort_en, country_id, lng_id, url, domain, confirmed, conf_user) VALUES 
	('20F', '20 Minutes',                   '20 Minutes',                   '20minutes',                  'FR', 'fr', 'http://www.20minutes.fr',              '20minutes.fr',                  1, 1),
	('20S', '20 Minutos',                   '20 Minutos',                   '20minutos',                  'ES', 'es', 'http://www.20minutos.es',              '20minutos.es',                  1, 1),
	('365', '365 Media',                    '365 Media',                    '365media',                   'IS', 'is', 'http://www.365midlar.is',              '365midlar.is',                  1, 1),
	('ABC', 'ABC',                          'ABC',                          'abc',                        'ES', 'es', 'http://www.abc.es',                    'abc.es',                        1, 1),
	('AFB', 'Aftonbladet',                  'Aftonbladet',                  'aftonbladet',                'SE', 'sv', 'http://www.aftonbladet.se',            'aftonbladet.se',                1, 1),
	('AGE', 'The Age',                      'The Age',                      'age',                        'AU', 'en', 'http://www.theage.com.au',             'theage.com.au',                 1, 1),
	('AHR', 'Al Ahram',                     'الأهرام‎',                     'ahram',                      'EG', 'ar', 'http://www.ahram.org.eg',              'ahram.org.eg',                  1, 1),
	('AJZ', 'Al Jazeera',                   '‏الجزيرة‎',                    'jazeera',                    'QA', 'en', 'http://www.aljazeera.com',             'aljazeera.com',                 1, 1),
	('AKB', 'Al Akhbar',                    'الأخبار‎',                     'akhbar',                     'LB', 'ar', 'http://www.al-akhbar.com',             'al-akhbar.com',                 1, 1),
	('AKI', 'AKIpress ',                    'АКИpress',                     'akipress',                   'KG', 'ru', 'http://www.akipress.org',              'akipress.org',                  1, 1),
	('AMY', 'Al Masry Al Youm',             'المصرى اليوم‎',                'masryalyoum',                'EG', 'ar', 'http://www.almasryalyoum.com',         'almasryalyoum.com',             1, 1),
	('APL', 'Asia-Plus',                    'Asia-Plus',                    'asiaplus',                   'TJ', 'en', 'http://news.tj',                       'news.tj',                       1, 1),
	('APN', 'Aftenposten',                  'Aftenposten',                  'aftenposten',                'NO', 'no', 'http://www.aftenposten.no',            'aftenposten.no',                1, 1),
	('APT', 'APTN',                         'APTN',                         'aptn',                       'CA', 'en', 'http://www.aptn.ca',                   'aptn.ca',                       1, 1),
	('ASH', 'Asahi Shimbun',                '朝日新聞',                         'asahishimbun',               'JP', 'ja', 'http://www.asahi.com',                 'asahi.com',                     1, 1),
	('AST', 'Asia Sentinel',                'Asia Sentinel',                'asiasentinel',               'MY', 'en', 'http://www.asiasentinel.com',          'asiasentinel.com',              1, 1),
	('AUS', 'The Australian',               'The Australian',               'australian',                 'AU', 'en', 'http://theaustralian.com.au',          'theaustralian.com.au',          1, 1),
	('BAL', 'Balkan Leaks',                 'Balkan Leaks',                 'balkanleaks',                'BG', 'bg', 'http://www.balkanleaks.eu',            'balkanleaks.eu',                1, 1),
	('BBC', 'BBC',                          'BBC',                          'bbc',                        'GB', 'en', 'http://www.bbc.co.uk',                 'bbc.co.uk',                     1, 1),
	('BGL', 'The Boston Globe',             'The Boston Globe',             'bostonglobe',                'US', 'en', 'http://www.bostonglobe.com',           'bostonglobe.com',               1, 1),
	('BIV', 'Bivol',                        'Биволъ',                       'bivol',                      'BG', 'bg', 'http://www.bivol.bg',                  'bivol.bg',                      1, 1),
	('BKP', 'Bangkok Post',                 'Bangkok Post',                 'bangkokpost',                'TH', 'en', 'http://www.bangkokpost.com',           'bangkokpost.com',               1, 1),
	('BLD', 'Bild',                         'Bild',                         'bild',                       'DE', 'de', 'http://www.bild.de',                   'bild.de',                       1, 1),
	('BRE', 'Brecha',                       'Brecha',                       'brecha',                     'UY', 'es', 'http://www.brecha.com.uy',             'brecha.com.uy',                 1, 1),
	('BRN', 'Belorusskiye Novosti',         'Белорусские новости',          'Belorusskiye Novosti',       'BY', 'ru', 'http://naviny.by',                     'naviny.by',                     1, 1),
	('BTG', 'Belfast Telegraph',            'Belfast Telegraph',            'belfasttelegraph',           'IE', 'en', 'http://www.belfasttelegraph.co.uk',    'belfasttelegraph.co.uk',        1, 1),
	('CBC', 'CBC',                          'CBC',                          'cbc',                        'CA', 'en', 'http://www.cbc.ca',                    'cbc.ca',                        1, 1),
	('CBL', 'Cabledrum',                    'Cabledrum',                    'cabledrum',                  'XX', 'en', 'http://www.cabledrum.net',             'cabledrum.net',                 1, 1),
	('CDS', 'Corriere della Sera',          'Corriere della Sera',          'corrieredellasera',          'IT', 'it', 'http://www.corriere.it',               'corriere.it',                   1, 1),
	('CHT', 'Chicago Tribune',              'Chicago Tribune',              'chicagotribune',             'US', 'en', 'http://www.chicagotribune.com',        'chicagotribune.com',            1, 1),
	('CIP', 'CIPER',                        'CIPER',                        'ciper',                      'CL', 'es', 'http://ciperchile.cl',                 'ciperchile.cl',                 1, 1),
	('CRJ', 'CRJI',                         'CRJI',                         'crji',                       'RO', 'ro', 'https://www.crji.org',                 'crji.org',                      1, 1),
	('CTP', 'CounterPunch',                 'CounterPunch',                 'counterpunch',               'US', 'en', 'http://www.counterpunch.org',          'counterpunch.org',              1, 1),
	('DAC', 'ABC Color',                    'ABC Color',                    'abccolor',                   'PY', 'es', 'http://www.abc.com.py',                'abc.com.py',                    1, 1),
	('DCC', 'Deccan Chronicle',             'Deccan Chronicle',             'deccanchronicle',            'IN', 'en', 'http://www.deccanchronicle.com',       'deccanchronicle.com',           1, 1),
	('DDN', 'Diário de Notícias',           'Diário de Notícias',           'diariodenoticias',           'PT', 'pt', 'http://www.dn.pt',                     'dn.pt',                         1, 1),
	('DEX', 'Daily Express',                'Daily Express',                'dailyexpress',               'GB', 'en', 'http://www.express.co.uk',             'express.co.uk',                 1, 1),
	('DML', 'Daily Mail',                   'Daily Mail',                   'dailymail',                  'GB', 'en', 'http://www.dailymail.co.uk',           'dailymail.co.uk',               1, 1),
	('DMR', 'Daily Mirror',                 'Daily Mirror',                 'dailymirror',                'GB', 'en', 'http://www.mirror.co.uk',              'mirror.co.uk',                  1, 1),
	('DNT', 'Daily Nation',                 'Daily Nation',                 'dailynation',                'KE', 'en', 'http://www.nation.co.ke',              'nation.co.ke',                  1, 1),
	('DNY', 'Dagens Nyheter',               'Dagens Nyheter',               'dagensnyheter',              'SE', 'sv', 'http://www.dn.se',                     'dn.se',                         1, 1),
	('DPL', 'Le Monde diplomatique',        'Le Monde diplomatique',        'mondediplomatique',          'FR', 'fr', 'http://www.monde-diplomatique.fr',     'monde-diplomatique.fr',         1, 1),
	('DST', 'Daily Star',                   'Daily Star',                   'dailystar',                  'GB', 'en', 'http://www.dailystar.co.uk',           'dailystar.co.uk',               1, 1),
	('DSU', 'Daily Sun',                    'Daily Sun',                    'dailysun',                   'SA', 'en', 'http://www.sunnewsonline.com',         'sunnewsonline.com',             1, 1),
	('DTL', 'De Telegraaf',                 'De Telegraaf',                 'detelegraaf',                'NL', 'nl', 'http://www.telegraaf.nl',              'telegraaf.nl',                  1, 1),
	('DWN', 'Dawn',                         'Dawn',                         'dawn',                       'PK', 'en', 'http://www.dawn.com',                  'dawn.com',                      1, 1),
	('DZT', 'Die Zeit',                     'Die Zeit',                     'zeit',                       'DE', 'de', 'http://www.zeit.de',                   'zeit.de',                       1, 1),
	('ECE', 'El Comercio',                  'El Comercio',                  'comercioecuador',            'EC', 'es', 'http://elcomercio.com',                'elcomercio.com',                1, 1),
	('ECO', 'The Economist',                'The Economist',                'economist',                  'GB', 'en', 'http://www.economist.com',             'economist.com',                 1, 1),
	('ECP', 'El Comercio',                  'El Comercio',                  'comercioperu',               'PE', 'es', 'http://elcomercio.pe',                 'elcomercio.pe',                 1, 1),
	('EFA', 'El Faro',                      'El Faro',                      'faro',                       'SV', 'es', 'http://www.elfaro.net',                'elfaro.net',                    1, 1),
	('EPA', 'El País',                      'El País',                      'pais',                       'ES', 'es', 'http://www.elpais.com',                'elpais.com',                    1, 1),
	('EPU', 'El País',                      'El País',                      'paisuruguay',                'UY', 'es', 'http://www.elpais.com.uy',             'elpais.com.uy',                 1, 1),
	('ESP', 'El Espectador',                'El Espectador',                'espectador',                 'CO', 'es', 'http://www.elespectador.com',          'elespectador.com',              1, 1),
	('EST', 'Estadão',                      'Estadão',                      'estadao',                    'BR', 'pt', 'http://topicos.estadao.com.br',        'topicos.estadao.com.br',        1, 1),
	('ETM', 'Economic Times',               'Economic Times',               'economictimes',              'IN', 'en', 'http://economictimes.indiatimes.com',  'economictimes.indiatimes.com',  1, 1),
	('EUN', 'El Universo',                  'El Universo',                  'universo',                   'EC', 'es', 'http://www.eluniverso.com',            'eluniverso.com',                1, 1),
	('FAC', 'FACT',                         'FACT',                         'fact',                       'TH', 'en', 'http://facthai.wordpress.com',         'facthai.wordpress.com',         1, 1),
	('FAZ', 'Frankfurter Allgemeine',       'Frankfurter Allgemeine',       'frankfurterallgemeine',      'DE', 'de', 'http://www.faz.net',                   'faz.net',                       1, 1),
	('FIG', 'Le Figaro',                    'Le Figaro',                    'figaro',                     'FR', 'fr', 'http://www.lefigaro.fr',               'lefigaro.fr',                   1, 1),
	('FKT', 'Fakt',                         'Fakt',                         'fakt',                       'PL', 'pl', 'http://www.e-fakt.pl',                 'e-fakt.pl',                     1, 1),
	('FOL', 'Folha',                        'Folha',                        'folha',                      'BR', 'pt', 'http://www.folha.uol.com.br',          'folha.uol.com.br',              1, 1),
	('FTI', 'Financial Times',              'Financial Times',              'financialtimes',             'GB', 'en', 'http://www.ft.com',                    'ft.com',                        1, 1),
	('GAM', 'The Globe and Mail',           'The Globe and Mail',           'globeandmail',               'CA', 'en', 'http://www.theglobeandmail.com',       'theglobeandmail.com',           1, 1),
	('GDN', 'The Guardian',                 'The Guardian',                 'guardian',                   'GB', 'en', 'http://www.guardian.co.uk',            'guardian.co.uk',                1, 1),
	('HAA', 'Haaretz',                      'Haaretz',                      'haaretz',                    'IL', 'en', 'http://www.haaretz.com',               'haaretz.com',                   1, 1),
	('HCR', 'Houston Chronicle',            'Houston Chronicle',            'houstonchronicle',           'US', 'en', 'http://chron.com',                     'chron.com',                     1, 1),
	('HLI', 'Haïti Liberté',                'Haïti Liberté',                'haitiliberte',               'HT', 'fr', 'http://www.haiti-liberte.com',         'haiti-liberte.com',             1, 1),
	('HLN', 'Het Laatste Nieuws',           'Het Laatste Nieuws',           'laatstenieuws',              'BE', 'nl', 'http://www.hln.be',                    'hln.be',                        1, 1),
	('HND', 'The Hindu',                    'The Hindu',                    'hindu',                      'IN', 'en', 'http://www.thehindu.com',              'thehindu.com',                  1, 1),
	('HRY', 'Hürriyet',                     'Hürriyet',                     'hurriyet',                   'TR', 'tr', 'http://www.hurriyet.com.tr',           'hurriyet.com.tr',               1, 1),
	('HSA', 'Helsingin Sanomat',            'Helsingin Sanomat',            'helsinginsanomat',           'FI', 'fi', 'http://www.hs.fi',                     'hs.fi',                         1, 1),
	('HTS', 'Hindustan Times',              'Hindustan Times',              'hindustantimes',             'IN', 'en', 'http://www.hindustantimes.com',        'hindustantimes.com',            1, 1),
	('IHT', 'International Herald Tribune', 'International Herald Tribune', 'internationalheraldtribune', 'US', 'en', 'http://global.nytimes.com',            'global.nytimes.com',            1, 1),
	('IND', 'The Independent',              'The Independent',              'independent',                'GB', 'en', 'http://www.independent.co.uk',         'independent.co.uk',             1, 1),
	('IRI', 'Irish Independent',            'Irish Independent',            'irishindependent',           'IE', 'en', 'http://www.independent.ie',            'independent.ie',                1, 1),
	('IRT', 'The Irish Times',              'The Irish Times',              'irishtimes',                 'IE', 'en', 'http://www.irishtimes.com',            'irishtimes.com',                1, 1),
	('IZV', 'Izvestia',                     'Известия',                     'izvestia',                   'RU', 'ru', 'http://www.izvestia.ru',               'izvestia.ru',                   1, 1),
	('JGL', 'The Gleaner',                  'The Gleaner',                  'gleaner',                    'JM', 'en', 'http://jamaica-gleaner.com',           'jamaica-gleaner.com',           1, 1),
	('KAT', 'Kathimerini',                  'Καθημερινή',                   'kathimerini',                'GR', 'el', 'http://news.kathimerini.gr',           'kathimerini.gr',                1, 1),
	('KAZ', 'KazTAG',                       'КазТАГ',                       'kaztag',                     'KZ', 'ru', 'http://kaztag.kz',                     'kaztag.kz',                     1, 1),
	('KPR', 'Komsomolskaja Prawda',         'Комсомольская правда',         'komsomolskajaprawda',        'RU', 'ru', 'http://www.kp.ru',                     'kp.ru',                         1, 1),
	('KRO', 'Kronen Zeitung',               'Kronen Zeitung',               'kronenzeitung',              'AT', 'de', 'http://www.krone.at',                  'krone.at',                      1, 1),
	('LAT', 'Los Angeles Times',            'Los Angeles Times',            'losangelestimes',            'US', 'en', 'http://www.latimes.com',               'latimes.com',                   1, 1),
	('LES', 'L’Espresso',                   'L’Espresso',                   'espresso',                   'IT', 'it', 'http://espresso.repubblica.it',        'espresso.repubblica.it',        1, 1),
	('LIB', 'Libération',                   'Libération',                   'libération',                 'FR', 'fr', 'http://www.liberation.fr',             'liberation.fr',                 1, 1),
	('LJR', 'La Jornada',                   'La Jornada',                   'jornada',                    'MX', 'es', 'http://www.jornada.unam.mx',           'jornada.unam.mx',               1, 1),
	('LMD', 'Le Monde',                     'Le Monde',                     'monde',                      'FR', 'fr', 'http://www.lemonde.fr',                'lemonde.fr',                    1, 1),
	('LNA', 'La Nación',                    'La Nación',                    'nacionargentina',            'AR', 'es', 'http://www.lanacion.com.ar',           'lanacion.com.ar',               1, 1),
	('LNC', 'La Nación',                    'La Nación',                    'nacioncostarica',            'CR', 'es', 'http://www.nacion.com',                'nacion.com',                    1, 1),
	('LPR', 'La Prensa',                    'La Prensa',                    'prensa',                     'PA', 'es', 'http://www.prensa.com',                'prensa.com',                    1, 1),
	('LQU', 'La Quadrature',                'La Quadrature',                'quadrature',                 'FR', 'fr', 'http://www.laquadrature.net',          'laquadrature.net',              1, 1),
	('MAL', 'Malaysia Today',               'Malaysia Today',               'malaysiatoday',              'MY', 'en', 'http://malaysia-today.net',            'malaysia-today.net',            1, 1),
	('MCC', 'McClatchy',                    'McClatchy',                    'mcclatchy',                  'US', 'en', 'http://www.mcclatchy.com',             'mcclatchy.com',                 1, 1),
	('MDP', 'Mediapart',                    'Mediapart',                    'mediapart',                  'FR', 'fr', 'http://www.mediapart.fr',              'mediapart.fr',                  1, 1),
	('MKO', 'Moskovskij Komsomolez',        'Московский комсомолец',        'moskovskijkomsomolez',       'RU', 'ru', 'http://www.mk.ru',                     'mk.ru',                         1, 1),
	('MND', 'El Mundo',                     'El Mundo',                     'mundo',                      'ES', 'es', 'http://www.elmundo.es',                'elmundo.es',                    1, 1),
	('MRC', 'El Mercurio',                  'El Mercurio',                  'mercurio',                   'CL', 'es', 'http://www.emol.com',                  'emol.com',                      1, 1),
	('NAW', 'Nawaat',                       'Nawaat',                       'nawaat',                     'TN', 'fr', 'http://nawaat.org',                    'nawaat.org',                    1, 1),
	('NDN', 'New York Daily News',          'New York Daily News',          'newyorkdailynews',           'US', 'en', 'http://www.nydailynews.com',           'nydailynews.com',               1, 1),
	('NDT', 'NDTV',                         'NDTV',                         'ndtv',                       'IN', 'en', 'http://www.ndtv.com',                  'ndtv.com',                      1, 1),
	('NEA', 'Ta Nea',                       'Τα Νέα',                       'tanea',                      'GR', 'el', 'http://www.tanea.gr',                  'tanea.gr',                      1, 1),
	('NEP', 'Népszabadság',                 'Népszabadság',                 'nepszabadsag',               'HU', 'hu', 'http://www.nol.hu',                    'nol.hu',                        1, 1),
	('NGZ', 'Novaya Gazeta',                'Новая газета',                 'novayagazeta',               'RU', 'ru', 'http://www.novayagazeta.ru',           'novayagazeta.ru',               1, 1),
	('NOS', 'NOS',                          'NOS',                          'nos',                        'NL', 'nl', 'http://www.nos.nl',                    'nos.nl',                        1, 1),
	('NRC', 'NRC Handelsblad',              'NRC Handelsblad',              'nrchandelsblad',             'NL', 'nl', 'http://www.nrc.nl',                    'nrc.nl',                        1, 1),
	('NYP', 'New York Post',                'New York Post',                'newyorkpost',                'US', 'en', 'http://www.nypost.com',                'nypost.com',                    1, 1),
	('NYT', 'The New York Times',           'The New York Times',           'newyorktimes',               'US', 'en', 'http://www.nytimes.com',               'nytimes.com',                   1, 1),
	('NZH', 'The New Zealand Herald',       'The New Zealand Herald',       'newzealandherald',           'NZ', 'en', 'http://www.nzherald.co.nz',            'nzherald.co.nz',                1, 1),
	('NZZ', 'Neue Zürcher Zeitung',         'Neue Zürcher Zeitung',         'neuezuercherzeitung',        'CH', 'de', 'http://www.nzz.ch',                    'nzz.ch',                        1, 1),
	('OBS', 'The Observer',                 'The Observer',                 'observer',                   'GB', 'en', 'http://observer.guardian.co.uk',       'observer.guardian.co.uk',       1, 1),
	('P12', 'Página/12',                    'Página/12',                    'pagina12',                   'AR', 'es', 'http://www.pagina12.com.ar',           'pagina12.com.ar',               1, 1),
	('PAM', 'Panamá América',               'Panamá América',               'panamaamerica',              'PA', 'es', 'http://www.panamaamerica.com.pa',      'panamaamerica.com.pa',          1, 1),
	('PLP', 'Plaza Pública',                'Plaza Pública',                'plazapublica',               'GT', 'es', 'http://plazapublica.com.gt',           'plazapublica.com.gt',           1, 1),
	('PLT', 'Politiken',                    'Politiken',                    'politiken',                  'DK', 'da', 'http://politiken.dk',                  'politiken.dk',                  1, 1),
	('POS', 'Posta',                        'Posta',                        'posta',                      'TR', 'tr', 'http://www.gazeteposta.net',           'gazeteposta.net',               1, 1),
	('PPP', 'The Phnom Penh Post',          'The Phnom Penh Post',          'phnompenhpost',              'KH', 'en', 'http://www.phnompenhpost.com',         'phnompenhpost.com',             1, 1),
	('PRN', 'Le Parisien',                  'Le Parisien',                  'parisien',                   'FR', 'fr', 'http://www.leparisien.com',            'leparisien.com',                1, 1),
	('PRS', 'La Presse',                    'La Presse',                    'presse',                     'CA', 'fr', 'http://www.cyberpresse.ca',            'cyberpresse.ca',                1, 1),
	('PST', 'Postimees',                    'Postimees',                    'postimees',                  'EE', 'et', 'http://www.postimees.ee',              'postimees.ee',                  1, 1),
	('PTA', 'Politika',                     'Политика',                     'politika',                   'RS', 'sr', 'http://www.politika.rs',               'politika.rs',                   1, 1),
	('PUB', 'Pública',                      'Pública',                      'publica',                    'BR', 'pt', 'http://apublica.org',                  'apublica.org',                  1, 1),
	('QUF', 'Ouest-France',                 'Ouest-France',                 'ouestfrance',                'FR', 'fr', 'http://www.ouest-france.fr',           'ouest-france.fr',               1, 1),
	('REP', 'La Repubblica',                'La Repubblica',                'repubblica',                 'IT', 'it', 'http://www.repubblica.it',             'repubblica.it',                 1, 1),
	('RES', 'Respublica',                   'Республика',                   'respublika',                 'KZ', 'ru', 'http://www.respublika-kz.info',        'respublika-kz.info',            1, 1),
	('REU', 'Reuters',                      'Reuters',                      'reuters',                    'GB', 'en', 'http://uk.reuters.com',                'uk.reuters.com',                1, 1),
	('RTD', 'Russia Today',                 'Russia Today',                 'russiatoday',                'RU', 'en', 'http://rt.com',                        'rt.com',                        1, 1),
	('RUR', 'Russkiy Reporter',             'Русский Репортёр',             'russkiyreporter',            'RU', 'ru', 'http://rusrep.ru',                     'rusrep.ru',                     1, 1),
	('RUV', 'RUV',                          'RÚV',                          'ruv',                        'IS', 'is', 'http://www.ruv.is',                    'ruv.is',                        1, 1),
	('SAS', 'The Star',                     'The Star',                     'starsa',                     'SA', 'en', 'http://www.thestar.co.za',             'thestar.co.za',                 1, 1),
	('SAT', 'The Times',                    'The Times',                    'timessa',                    'SA', 'en', 'http://www.thetimes.co.za',            'thetimes.co.za',                1, 1),
	('SCO', 'The Scotsman ',                'The Scotsman ',                'scotsman',                   'GB', 'en', 'http://www.scotsman.com',              'scotsman.com',                  1, 1),
	('SCS', 'Scotland on Sunday',           'Scotland on Sunday',           'scotlandonsunday',           'GB', 'en', 'http://scotlandonsunday.scotsman.com', 'scotlandonsunday.scotsman.com', 1, 1),
	('SDB', 'Svenska Dagbladet',            'Svenska Dagbladet',            'svenskadagbladet',           'SE', 'sv', 'http://www.svd.se',                    'svd.se',                        1, 1),
	('SDZ', 'Süddeutsche Zeitung',          'Süddeutsche Zeitung',          'suddeutschezeitung',         'DE', 'de', 'http://www.sueddeutsche.de',           'sueddeutsche.de',               1, 1),
	('SEM', 'Semana',                       'Semana',                       'semana',                     'CO', 'es', 'http://www.semana.com',                'semana.com',                    1, 1),
	('SFC', 'San Francisco Chronicle',      'San Francisco Chronicle',      'sanfranciscochronicle',      'US', 'en', 'http://www.sfgate.com',                'sfgate.com',                    1, 1),
	('SIN', 'SIN',                          'SIN',                          'sin',                        'DO', 'es', 'http://www.noticiassin.com',           'noticiassin.com',               1, 1),
	('SMH', 'Sydney Morning Herald',        'Sydney Morning Herald',        'sydneymorningherald',        'AU', 'en', 'http://www.smh.com.au',                'smh.com.au',                    1, 1),
	('SON', 'Die Son',                      'Die Son',                      'son',                        'SA', 'af', 'http://www.dieson.co.za',              'dieson.co.za',                  1, 1),
	('SOV', 'Sov Sekretno',                 'Совершенно секретно',          'sovsekretno',                'RU', 'ru', 'http://www.sovsekretno.ru',            'sovsekretno.ru',                1, 1),
	('SOW', 'The Sowetan',                  'The Sowetan',                  'sowetan',                    'SA', 'en', 'http://www.sowetan.co.za',             'sowetan.co.za',                 1, 1),
	('SPG', 'Der Spiegel',                  'Der Spiegel',                  'spiegel',                    'DE', 'de', 'http://www.spiegel.de',                'spiegel.de',                    1, 1),
	('SST', 'Sunday Star Times',            'Sunday Star Times',            'sundaystartimes',            'NZ', 'en', 'http://sundaystartimes.co.nz',         'sundaystartimes.co.nz',         1, 1),
	('STD', 'De Standaard',                 'De Standaard',                 'standaard',                  'BE', 'nl', 'http://www.standaard.be',              'standaard.be',                  1, 1),
	('STN', 'Stern',                        'Stern',                        'stern',                      'DE', 'de', 'http://www.stern.de',                  'stern.de',                      1, 1),
	('STR', 'The Star',                     'The Star',                     'star',                       'KE', 'en', 'http://www.the-star.co.ke',            'the-star.co.ke',                1, 1),
	('SUN', 'The Sun',                      'The Sun',                      'sun',                        'GB', 'en', 'http://www.thesun.co.uk',              'thesun.co.uk',                  1, 1),
	('SVT', 'Sveriges Television',          'Sveriges Television',          'sverigestelevision',         'SE', 'sv', 'http://svt.se',                        'svt.se',                        1, 1),
	('TAR', 'Taraf',                        'Taraf',                        'taraf',                      'TR', 'tr', 'http://www.taraf.com.tr',              'taraf.com.tr',                  1, 1),
	('TJP', 'The Jerusalem Post',           'The Jerusalem Post',           'jerusalempost',              'IL', 'en', 'http://www.jpost.com',                 'jpost.com',                     1, 1),
	('TLG', 'The Telegraph',                'The Telegraph',                'telegraph',                  'GB', 'en', 'http://www.telegraph.co.uk',           'telegraph.co.uk',               1, 1),
	('TMP', 'Le Temps',                     'Le Temps',                     'temps',                      'CH', 'fr', 'http://www.letemps.ch',                'letemps.ch',                    1, 1),
	('TMS', 'The Times',                    'The Times',                    'times',                      'GB', 'en', 'http://www.thetimes.co.uk',            'thetimes.co.uk',                1, 1),
	('TOI', 'The Times of India',           'The Times of India',           'timesofindia',               'IN', 'en', 'http://timesofindia.indiatimes.com',   'timesofindia.indiatimes.com',   1, 1),
	('USA', 'USA Today',                    'USA Today',                    'usatoday',                   'US', 'en', 'http://www.usatoday.com',              'usatoday.com',                  1, 1),
	('VRG', 'Verdens Gang',                 'Verdens Gang',                 'verdensgang',                'NO', 'no', 'http://www.vg.no',                     'vg.no',                         1, 1),
	('WLC', 'WikiLeaks Central',            'WikiLeaks Central',            'wikiLeakscentral',           'XX', 'en', 'http://wlcentral.org',                 'wlcentral.org',                 1, 1),
	('WLK', 'WikiLeaks',                    'WikiLeaks',                    'wikiLeaks',                  'XX', 'en', 'http://wikileaks.org',                 'wikileaks.org',                 1, 1),
	('WLT', 'Die Welt',                     'Die Welt',                     'welt',                       'DE', 'de', 'http://welt.de',                       'welt.de',                       1, 1),
	('WPT', 'The Washington Post',          'The Washington Post',          'washingtonpost',             'US', 'en', 'http://www.washingtonpost.com',        'washingtonpost.com',            1, 1),
	('WSJ', 'The Wall Street Journal',      'The Wall Street Journal',      'thewallstreetjournal',       'US', 'en', 'http://www.wsj.com',                   'wsj.com',                       1, 1),
	('YEA', 'Yedioth Ahronoth',             'ויקיפדיה',                     'yediothahronoth',            'IL', 'he', 'http://www.ynet.co.il',                'ynet.co.il',                    1, 1),
	('YLE', 'YLE',                          'YLE',                          'yle',                        'FI', 'fi', 'http://www.yle.fi',                    'yle.fi',                        1, 1),
	('ZAM', 'Zaman',                        'Zaman',                        'zaman',                      'TR', 'tr', 'http://www.zaman.com.tr',              'zaman.com.tr',                  1, 1);

-- ***
